# Generated by Django 6.0.3 on 2026-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('success', 'Success'), ('error', 'Error'), ('system', 'System')], default='order_update', max_length=20),
        ),
    ]
