# Generated by Django 6.0.3 on 2026-03-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_notification_type'),
        ('products', '0009_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize'),
        ),
    ]
