# Generated by Django 6.0.3 on 2026-03-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_variant'),
        ('products', '0010_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_label',
            field=models.CharField(blank=True, help_text='Text fallback for size', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize'),
        ),
    ]
