# Generated by Django 6.0.3 on 2026-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_image_url_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=20)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
