# Generated by Django 6.0.3 on 2026-03-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sitecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
