# Generated by Django 6.0.3 on 2026-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_display_order_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection_name',
            field=models.CharField(blank=True, help_text='e.g. Summer 2024', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Percentage off base price'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archive_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
