# Generated by Django 6.0.3 on 2026-03-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_variant'),
        ('products', '0009_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
