# Generated by Django 6.0.3 on 2026-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('bestsellers', 'Best Sellers'), ('featured', 'Featured Products'), ('trending', 'Trending Now'), ('new_arrivals', 'New Arrivals'), ('categories', 'Category Grid'), ('newsletter', 'Newsletter Sign-up')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
